### PR TITLE
Tweaked build setup, annotate pure calls, use tslib

### PR DESCRIPTION
**Pull request by Andarist**
I've made few changes that makes this lib smaller + more tree-shakeable. Additionally I got rid of pesky rollup warnings.

If you have any question about any change here, please just ask.

PS. If you accept those changes, I'm gonna audit rest of popmotion family of libraries and send similar PRs there too.

### CODE REVIEW

**Comment by InventingWithMonster** [comment]
Hey man, thanks for this! Always excited to reduce bundle size.

Just a couple q’s:

What’s the before/after size using npm run measure?

Also what does the external predicate function do? I assumed including external packages in the non-umd Rollup output could duplicate code should someone be using both the library and one of its dependencies?

**Comment by Andarist** [comment]
> What’s the before/after size using npm run measure?

pre 3659
post 2683

Actually this result is a little bit surprising to me, I've expected only a really minor change. This might be caused be some deps being previously included in umd bundle (instead of being required as external dep).

> Also what does the external predicate function do?

This is just a future-proof guard. Normally it's enought to include list of dependencies + peerDependencies, but this list is compared strictly against requested IDs. This RegExp takes care of "deep imported" deps, in example `import uniq from 'lodash/uniq'`.

> I assumed including external packages in the non-umd Rollup output could duplicate code should someone be using both the library and one of its dependencies?


Could u rephrase? I'm not sure if I got ur question right - by it's unfortunately super easy to include external deps in ur bundles if you do not use `external` option and by that u effectively duplicate ur deps code inside ur bundle and ofc this prevents npm deduping those across dependencies etc.

**Comment by InventingWithMonster** [comment]
I think you're right about the missing deps. I'm trying to output the minified versions with all required dependencies included (for use in CodePen etc) - is it possible to revert this specific bundle so it does include external deps?

What I was getting at with that last comment, I was worried about including the external dependencies as, like you say, that might result in duplicated code. But I see what you've done to remove the warnings doesn't actually include them in the output. Nice!

Thanks for your explanations!

**Comment by Andarist** [comment]
Please take a look now, I've tweaked the configs in a way that umd builds include all externals **except** peers (u dont have peers though 😉). This obviously increases umd bundle size, so I've changed the measure script to run on commonjs file. This lands us on *2585* bytes (it's smaller because umd obviously included umd wrapper, which is not needed here).

**Comment by Andarist** [comment]
I will take a look at all popmotion libs in the weekend. 

> @Andarist If it's measuring $npm_package_main, doesn't that mean it's being measured without its deps?

Yeah, I usually measure only source code of the library in question. Measurements with deps are also useful, but IMHO harder to maintain in a long run. U can adjust it however u see fit - it's debatable which one is better.

**Pull request merged**
